name: "Check requirements files"
description: "Set up pip-tools, recompile requirements files, and fail if there are changes."
inputs:
  wdl-file:
    description: "The WDL file to check."
    required: true
  womtool-version:
    description: "The version of womtool to use."
    required: false
    default: "87"
  java-version:
    description: "The version of Java to use."
    required: false
    default: "11"

runs:
  using: "composite"
  steps:

      # Install Java to this VM. This Java version and distribution is compatible with Cromwell.
      # This is the same step as used by broadinstitute/cromwell/.github/set_up_cromwell_action.
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      # Get cromwell jar file
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: 'broadinstitute/cromwell'
          tag: '${{ inputs.womtool-version }}'
          fileName: 'womtool-${{ inputs.womtool-version }}.jar'

      - name: Run womtool
        run: java -jar womtool-${{ inputs.womtool-version }}.jar validate ${{ inputs.wdl-file }}
        shell: bash
