name: "Check requirements files"
description: "Set up pip-tools, recompile requirements files, and fail if there are changes."
inputs:
  wdl-file:
    description: "The WDL file to check."
    required: true


runs:
  using: "composite"
  steps:

      # Install Java to this VM. This Java version and distribution is compatible with Cromwell.
      # This is the same step as used by broadinstitute/cromwell/.github/set_up_cromwell_action.
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      # Get cromwell jar file
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: 'broadinstitute/cromwell'
          tag: '87'
          fileName: 'womtool-87.jar'

      - name: Run womtool
        run: java -jar womtool-87.jar validate ${{ inputs.wdl-file }}
        shell: bash
